### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by zhywanna** [nex-mpi/nex-code#38]
my gpu: nvidia 1080Ti * 4

Loading  Model @ Epoch 4000
"train.py" in <module>
  751:  train()
  train.py
"train.py" in train
  584:  generateAlpha(model, dataset, dataloader_val, None, runpath, dataloader_train = dataloader_train)
  train.py
"train.py" in generateAlpha
  494:  info = getMPI(model, dataset.sfm, dataloader = dataloader_train)
  train.py
"train.py" in getMPI
  455:  out = model.seq1(bigcoords)
  train.py
"module.py" in _call_impl
  889:  result = self.forward(*input, **kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py
"data_parallel.py" in forward
  167:  outputs = self.parallel_apply(replicas, inputs, kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"data_parallel.py" in parallel_apply
  177:  return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"parallel_apply.py" in parallel_apply
   86:  output.reraise()
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py
"_utils.py" in reraise
  429:  raise self.exc_type(msg)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/_utils.py
RuntimeError: Caught RuntimeError in replica 0 on device 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nex/utils/mlp.py", line 29, in forward
    return self.seq1(x)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 714, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/functional.py", line 1378, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA out of memory. Tried to allocate 3.51 GiB (GPU 1; 10.92 GiB total capacity; 4.26 GiB already allocated; 2.61 GiB free; 7.55 GiB reserved in total by PyTorch)

**Comment by zhywanna** [comment]
it happened after the line "Finished Training"

**Comment by pureexe** [comment]
**7.55 GiB reserved in total by PyTorch** 

I'm not sure what happened here. but it seems like PyTorch eating up a lot of memory. 

1. reboot your machine.
2. If problem still persist, add `pt.cuda.empty_cache()` before call getMPI

**Comment by zhywanna** [comment]
thanks for your reply！i add `pt.cuda.empty_cache()`here but the error still happened...
![image](https://user-images.githubusercontent.com/47680024/139650295-6fe973ff-6603-49a7-848e-ddd02f0c29b4.png)

![image](https://user-images.githubusercontent.com/47680024/139649698-126135ca-f889-48f9-8e6f-0f7ff560ef70.png)
![image](https://user-images.githubusercontent.com/47680024/139649725-d19af2b5-b3cc-4af7-9ef1-2496cd205c8b.png)
![image](https://user-images.githubusercontent.com/47680024/139649753-e3039187-619b-49b8-b305-58d52d7dd4de.png)

In addition, it happened when i use my own dataset. However, I can run your crest_demo without any problem.

**Comment by zhywanna** [comment]
![image](https://user-images.githubusercontent.com/47680024/139638525-c5adfd60-b05f-4bb1-8509-b7af476444d7.png)
![image](https://user-images.githubusercontent.com/47680024/139638550-3fa9b9a7-a2e2-44e9-9f33-67d91df1fa7a.png)

**Comment by zhywanna** [comment]
(nex) root@3cab2c9079bb:/nex# python train.py -scene data/juice -model_dir juice
Loaded data/juice 1.6558311137399147 31.816099112601034
recentered (3, 4)
dmin = 2.168455, dmax = 14.218433, invz = 0, offset = 200
TRAINING IMAGES: 42
VALIDATE IMAGES: 6
Basis Network: DataParallel(
  (module): ReluMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=12, out_features=64, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=64, out_features=8, bias=True)
    )
  )
)
Mpi Size: torch.Size([16, 3, 1744, 1408])
All combined layers: 192
[ 2.16845489  2.23154378  2.29463267  2.35772156  2.42081046  2.48389935
  2.54698824  2.61007713  2.67316603  2.73625492  2.79934381  2.8624327
  2.9255216   2.98861049  3.05169938  3.11478828  3.17787717  3.24096606
  3.30405495  3.36714385  3.43023274  3.49332163  3.55641052  3.61949942
  3.68258831  3.7456772   3.80876609  3.87185499  3.93494388  3.99803277
  4.06112166  4.12421056  4.18729945  4.25038834  4.31347724  4.37656613
  4.43965502  4.50274391  4.56583281  4.6289217   4.69201059  4.75509948
  4.81818838  4.88127727  4.94436616  5.00745505  5.07054395  5.13363284
  5.19672173  5.25981062  5.32289952  5.38598841  5.4490773   5.5121662
  5.57525509  5.63834398  5.70143287  5.76452177  5.82761066  5.89069955
  5.95378844  6.01687734  6.07996623  6.14305512  6.20614401  6.26923291
  6.3323218   6.39541069  6.45849959  6.52158848  6.58467737  6.64776626
  6.71085516  6.77394405  6.83703294  6.90012183  6.96321073  7.02629962
  7.08938851  7.1524774   7.2155663   7.27865519  7.34174408  7.40483297
  7.46792187  7.53101076  7.59409965  7.65718855  7.72027744  7.78336633
  7.84645522  7.90954412  7.97263301  8.0357219   8.09881079  8.16189969
  8.22498858  8.28807747  8.35116636  8.41425526  8.47734415  8.54043304
  8.60352193  8.66661083  8.72969972  8.79278861  8.85587751  8.9189664
  8.98205529  9.04514418  9.10823308  9.17132197  9.23441086  9.29749975
  9.36058865  9.42367754  9.48676643  9.54985532  9.61294422  9.67603311
  9.739122    9.8022109   9.86529979  9.92838868  9.99147757 10.05456647
 10.11765536 10.18074425 10.24383314 10.30692204 10.37001093 10.43309982
 10.49618871 10.55927761 10.6223665  10.68545539 10.74854428 10.81163318
 10.87472207 10.93781096 11.00089986 11.06398875 11.12707764 11.19016653
 11.25325543 11.31634432 11.37943321 11.4425221  11.505611   11.56869989
 11.63178878 11.69487767 11.75796657 11.82105546 11.88414435 11.94723325
 12.01032214 12.07341103 12.13649992 12.19958882 12.26267771 12.3257666
 12.38885549 12.45194439 12.51503328 12.57812217 12.64121106 12.70429996
 12.76738885 12.83047774 12.89356663 12.95665553 13.01974442 13.08283331
 13.14592221 13.2090111  13.27209999 13.33518888 13.39827778 13.46136667
 13.52445556 13.58754445 13.65063335 13.71372224 13.77681113 13.83990002
 13.90298892 13.96607781 14.0291667  14.09225559 14.15534449 14.21843338]
Using inverse depth: False, Min depth: 2.168454885482788, Max depth: 14.218433380126953
Layer of MLP: 6
Hidden Channel of MLP: 384
Main Network DataParallel(
  (module): VanillaMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=56, out_features=384, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=384, out_features=384, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=384, out_features=384, bias=True)
      (5): LeakyReLU(negative_slope=0.01)
      (6): Linear(in_features=384, out_features=384, bias=True)
      (7): LeakyReLU(negative_slope=0.01)
      (8): Linear(in_features=384, out_features=384, bias=True)
      (9): LeakyReLU(negative_slope=0.01)
      (10): Linear(in_features=384, out_features=25, bias=True)
    )
  )
)
Loading  Model @ Epoch 4000
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]                                              
Loading model from: /root/anaconda3/envs/nex/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth                 
===================================
Measurement Result
===================================
                         name       PSNR      SSIM       LPIPS
 images_20211014_IMG_4527.JPG  26.054576  0.916474  0.48331454
 images_20211014_IMG_4477.JPG  27.533089  0.928617  0.42879075
 images_20211014_IMG_4485.JPG  27.682252  0.928262  0.42575046
 images_20211014_IMG_4469.JPG  21.773386  0.887331  0.51094466
 images_20211014_IMG_4519.JPG  25.937082  0.927995   0.4745805
 images_20211014_IMG_4511.JPG  26.476935  0.921743  0.42415673
-----------------------------------
PSNR     25.909553
SSIM      0.918404
LPIPS     0.457923
Finished Training
"train.py" in <module>
  751:  train()
  train.py
"train.py" in train
  693:  generateAlpha(model, dataset, dataloader_val, None, runpath, dataloader_train = dataloader_train)
  train.py
"train.py" in generateAlpha
  494:  info = getMPI(model, dataset.sfm, dataloader = dataloader_train)
  train.py
"train.py" in getMPI
  455:  out = model.seq1(bigcoords)
  train.py
"module.py" in _call_impl
  889:  result = self.forward(*input, **kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py
"data_parallel.py" in forward
  167:  outputs = self.parallel_apply(replicas, inputs, kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"data_parallel.py" in parallel_apply
  177:  return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"parallel_apply.py" in parallel_apply
   86:  output.reraise()
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py
"_utils.py" in reraise
  429:  raise self.exc_type(msg)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/_utils.py
RuntimeError: Caught RuntimeError in replica 0 on device 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nex/utils/mlp.py", line 29, in forward
    return self.seq1(x)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 714, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/functional.py", line 1378, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA out of memory. Tried to allocate 3.51 GiB (GPU 1; 10.92 GiB total capacity; 4.26 GiB already allocated; 2.58 GiB free; 7.57 GiB reserved in total by PyTorch)

**Comment by zhywanna** [comment]
(nex) root@3cab2c9079bb:/nex# python train.py -scene data/juice -model_dir juice
Loaded data/juice 1.6558311137399147 31.816099112601034
recentered (3, 4)
dmin = 2.168455, dmax = 14.218433, invz = 0, offset = 200
TRAINING IMAGES: 42
VALIDATE IMAGES: 6
Basis Network: DataParallel(
  (module): ReluMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=12, out_features=64, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=64, out_features=8, bias=True)
    )
  )
)
Mpi Size: torch.Size([16, 3, 1744, 1408])
All combined layers: 192
[ 2.16845489  2.23154378  2.29463267  2.35772156  2.42081046  2.48389935
  2.54698824  2.61007713  2.67316603  2.73625492  2.79934381  2.8624327
  2.9255216   2.98861049  3.05169938  3.11478828  3.17787717  3.24096606
  3.30405495  3.36714385  3.43023274  3.49332163  3.55641052  3.61949942
  3.68258831  3.7456772   3.80876609  3.87185499  3.93494388  3.99803277
  4.06112166  4.12421056  4.18729945  4.25038834  4.31347724  4.37656613
  4.43965502  4.50274391  4.56583281  4.6289217   4.69201059  4.75509948
  4.81818838  4.88127727  4.94436616  5.00745505  5.07054395  5.13363284
  5.19672173  5.25981062  5.32289952  5.38598841  5.4490773   5.5121662
  5.57525509  5.63834398  5.70143287  5.76452177  5.82761066  5.89069955
  5.95378844  6.01687734  6.07996623  6.14305512  6.20614401  6.26923291
  6.3323218   6.39541069  6.45849959  6.52158848  6.58467737  6.64776626
  6.71085516  6.77394405  6.83703294  6.90012183  6.96321073  7.02629962
  7.08938851  7.1524774   7.2155663   7.27865519  7.34174408  7.40483297
  7.46792187  7.53101076  7.59409965  7.65718855  7.72027744  7.78336633
  7.84645522  7.90954412  7.97263301  8.0357219   8.09881079  8.16189969
  8.22498858  8.28807747  8.35116636  8.41425526  8.47734415  8.54043304
  8.60352193  8.66661083  8.72969972  8.79278861  8.85587751  8.9189664
  8.98205529  9.04514418  9.10823308  9.17132197  9.23441086  9.29749975
  9.36058865  9.42367754  9.48676643  9.54985532  9.61294422  9.67603311
  9.739122    9.8022109   9.86529979  9.92838868  9.99147757 10.05456647
 10.11765536 10.18074425 10.24383314 10.30692204 10.37001093 10.43309982
 10.49618871 10.55927761 10.6223665  10.68545539 10.74854428 10.81163318
 10.87472207 10.93781096 11.00089986 11.06398875 11.12707764 11.19016653
 11.25325543 11.31634432 11.37943321 11.4425221  11.505611   11.56869989
 11.63178878 11.69487767 11.75796657 11.82105546 11.88414435 11.94723325
 12.01032214 12.07341103 12.13649992 12.19958882 12.26267771 12.3257666
 12.38885549 12.45194439 12.51503328 12.57812217 12.64121106 12.70429996
 12.76738885 12.83047774 12.89356663 12.95665553 13.01974442 13.08283331
 13.14592221 13.2090111  13.27209999 13.33518888 13.39827778 13.46136667
 13.52445556 13.58754445 13.65063335 13.71372224 13.77681113 13.83990002
 13.90298892 13.96607781 14.0291667  14.09225559 14.15534449 14.21843338]
Using inverse depth: False, Min depth: 2.168454885482788, Max depth: 14.218433380126953
Layer of MLP: 6
Hidden Channel of MLP: 384
Main Network DataParallel(
  (module): VanillaMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=56, out_features=384, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=384, out_features=384, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=384, out_features=384, bias=True)
      (5): LeakyReLU(negative_slope=0.01)
      (6): Linear(in_features=384, out_features=384, bias=True)
      (7): LeakyReLU(negative_slope=0.01)
      (8): Linear(in_features=384, out_features=384, bias=True)
      (9): LeakyReLU(negative_slope=0.01)
      (10): Linear(in_features=384, out_features=25, bias=True)
    )
  )
)
Loading  Model @ Epoch 4000
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]                                              
Loading model from: /root/anaconda3/envs/nex/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth                 
===================================
Measurement Result
===================================
                         name       PSNR      SSIM       LPIPS
 images_20211014_IMG_4527.JPG  26.054576  0.916474  0.48331454
 images_20211014_IMG_4477.JPG  27.533089  0.928617  0.42879075
 images_20211014_IMG_4485.JPG  27.682252  0.928262  0.42575046
 images_20211014_IMG_4469.JPG  21.773386  0.887331  0.51094466
 images_20211014_IMG_4519.JPG  25.937082  0.927995   0.4745805
 images_20211014_IMG_4511.JPG  26.476935  0.921743  0.42415673
-----------------------------------
PSNR     25.909553
SSIM      0.918404
LPIPS     0.457923
Finished Training
"train.py" in <module>
  751:  train()
  train.py
"train.py" in train
  693:  generateAlpha(model, dataset, dataloader_val, None, runpath, dataloader_train = dataloader_train)
  train.py
"train.py" in generateAlpha
  494:  info = getMPI(model, dataset.sfm, dataloader = dataloader_train)
  train.py
"train.py" in getMPI
  455:  out = model.seq1(bigcoords)
  train.py
"module.py" in _call_impl
  889:  result = self.forward(*input, **kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py
"data_parallel.py" in forward
  167:  outputs = self.parallel_apply(replicas, inputs, kwargs)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"data_parallel.py" in parallel_apply
  177:  return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py
"parallel_apply.py" in parallel_apply
   86:  output.reraise()
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py
"_utils.py" in reraise
  429:  raise self.exc_type(msg)
  /root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/_utils.py
RuntimeError: Caught RuntimeError in replica 0 on device 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nex/utils/mlp.py", line 29, in forward
    return self.seq1(x)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 714, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/root/anaconda3/envs/nex/lib/python3.8/site-packages/torch/nn/functional.py", line 1378, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA out of memory. Tried to allocate 3.51 GiB (GPU 1; 10.92 GiB total capacity; 4.26 GiB already allocated; 2.58 GiB free; 7.57 GiB reserved in total by PyTorch)
